export const INVENTORY_WORKFLOW = {
  name: 'Complete Inventory Management Workflow',
  description: 'End-to-end workflow from material requirements check through inventory management',
  phases: [
    {
      id: 'quotation',
      name: 'Planning & Quotation',
      description: 'Material requirements review and quotation request',
      color: 'blue'
    },
    {
      id: 'purchase',
      name: 'Purchase Phase',
      description: 'Purchase order creation and dispatch',
      color: 'purple'
    },
    {
      id: 'receipt',
      name: 'Receipt Phase',
      description: 'Material receipt and PO approval',
      color: 'indigo'
    },
    {
      id: 'quality',
      name: 'Quality Phase',
      description: 'GRN processing and QC inspection',
      color: 'amber'
    },
    {
      id: 'storage',
      name: 'Storage Phase',
      description: 'Stock storage and reorder management',
      color: 'green'
    },
    {
      id: 'usage',
      name: 'Usage Phase',
      description: 'Stock tracking and movements',
      color: 'cyan'
    }
  ],
  steps: [
    {
      id: 1,
      title: 'Check Project Material Requirements',
      description: 'Review and verify all material requirements for the project from procurement',
      phase: 'quotation',
      category: 'Material Planning',
      page: '/procurement/material-requirements',
      icon: 'FileText',
      priority: 'critical',
      order: 1,
    },
    {
      id: 2,
      title: 'Create RFQ Quotation',
      description: 'Create Request for Quotation (RFQ) for required materials from vendors',
      phase: 'quotation',
      category: 'Procurement',
      page: '/inventory-manager/vendors/quotations',
      icon: 'FileText',
      priority: 'high',
      order: 2,
    },
    {
      id: 3,
      title: 'Send Quotation to Vendor',
      description: 'Send RFQ quotation to vendor via email',
      phase: 'quotation',
      category: 'Procurement',
      page: '/inventory-manager/vendors/quotations',
      icon: 'Mail',
      priority: 'high',
      order: 3,
    },
    {
      id: 4,
      title: 'Receive Vendor Quotation',
      description: 'Receive and review vendor quotation response',
      phase: 'purchase',
      category: 'Procurement',
      page: '/inventory-manager/vendors/quotations',
      icon: 'CheckCircle',
      priority: 'high',
      order: 4,
    },
    {
      id: 5,
      title: 'Create Purchase Order',
      description: 'Create Purchase Order based on vendor quotation',
      phase: 'purchase',
      category: 'Procurement',
      page: '/inventory-manager/vendors/po',
      icon: 'Package',
      priority: 'high',
      order: 5,
    },
    {
      id: 6,
      title: 'Send PO to Vendor',
      description: 'Send Purchase Order to vendor via email',
      phase: 'purchase',
      category: 'Procurement',
      page: '/inventory-manager/vendors/po',
      icon: 'Mail',
      priority: 'high',
      order: 6,
    },
    {
      id: 7,
      title: 'Receive Material',
      description: 'Receive material from vendor at warehouse',
      phase: 'receipt',
      category: 'Receiving',
      page: '/inventory-manager/qc/grn',
      icon: 'TrendingDown',
      priority: 'high',
      order: 7,
    },
    {
      id: 8,
      title: 'Approve Purchase Order',
      description: 'Approve PO after material receipt verification',
      phase: 'receipt',
      category: 'Receiving',
      page: '/inventory-manager/vendors/po',
      icon: 'CheckCircle',
      priority: 'high',
      order: 8,
    },
    {
      id: 9,
      title: 'GRN Processing',
      description: 'Process Goods Receipt Note (GRN) for received material',
      phase: 'quality',
      category: 'Quality Control',
      page: '/inventory-manager/qc/grn',
      icon: 'CheckCircle',
      priority: 'high',
      order: 9,
    },
    {
      id: 10,
      title: 'QC Inspection',
      description: 'Perform quality control inspection (accept/reject)',
      phase: 'quality',
      category: 'Quality Control',
      page: '/inventory-manager/qc/inspections',
      icon: 'CheckCircle',
      priority: 'high',
      order: 10,
    },
    {
      id: 11,
      title: 'Stock Addition',
      description: 'Add inspected materials to stock inventory',
      phase: 'storage',
      category: 'Stock Management',
      page: '/inventory-manager/stock/view',
      icon: 'Package',
      priority: 'high',
      order: 11,
    },
    {
      id: 12,
      title: 'Batch & Location Management',
      description: 'Create batches and assign rack/shelf locations',
      phase: 'storage',
      category: 'Inventory Tracking',
      page: '/inventory-manager/tracking/batches',
      icon: 'Boxes',
      priority: 'medium',
      order: 12,
    },
    {
      id: 13,
      title: 'View Stock',
      description: 'View and monitor available stock levels',
      phase: 'usage',
      category: 'Stock Management',
      page: '/inventory-manager/stock/view',
      icon: 'Eye',
      priority: 'medium',
      order: 13,
    },
    {
      id: 14,
      title: 'Stock Movements',
      description: 'Track stock in/out movements and issuances',
      phase: 'usage',
      category: 'Stock Management',
      page: '/inventory-manager/stock/movements',
      icon: 'RefreshCw',
      priority: 'medium',
      order: 14,
    },
    {
      id: 15,
      title: 'Reorder Levels Review',
      description: 'Monitor and update reorder levels for materials',
      phase: 'usage',
      category: 'Stock Management',
      page: '/inventory-manager/stock/reorder',
      icon: 'AlertTriangle',
      priority: 'medium',
      order: 15,
    },
  ]
};

export const generateWorkflowTasks = (rootCardData, roleId = 2) => {
  return INVENTORY_WORKFLOW.steps.map((step, index) => ({
    title: step.title,
    description: step.description,
    priority: step.priority,
    status: 'pending',
    roleId: roleId,
    rootCardId: rootCardData?.id,
    project: rootCardData?.project || {},
    notes: JSON.stringify({
      workflow_step: index + 1,
      total_steps: INVENTORY_WORKFLOW.steps.length,
      category: step.category,
      page: step.page,
      icon: step.icon,
      phase: step.phase,
    }),
  }));
};

export const getWorkflowStep = (stepNumber) => {
  return INVENTORY_WORKFLOW.steps[stepNumber - 1] || null;
};
