const express = require('express');
const router = express.Router();
const authMiddleware = require('../../middleware/authMiddleware');
const roleMiddleware = require('../../middleware/roleMiddleware');
const productionController = require('../../controllers/production/productionController');

router.use(authMiddleware);

router.get('/root-cards', roleMiddleware('Admin', 'Management', 'Production', 'Design Engineer'), productionController.getRootCards);
router.post('/root-cards', roleMiddleware('Admin', 'Management'), productionController.createRootCard);
router.get('/root-cards/:id', roleMiddleware('Admin', 'Management', 'Production'), productionController.getRootCardById);
router.put('/root-cards/:id', roleMiddleware('Admin', 'Management'), productionController.updateRootCard);
router.delete('/root-cards/:id', roleMiddleware('Admin', 'Management'), productionController.deleteRootCard);
router.post('/root-cards/:rootCardId/auto-generate-tasks', roleMiddleware('Admin', 'Management'), productionController.autoGenerateDesignTasks);
router.post('/root-cards/:rootCardId/workflow-tasks', roleMiddleware('Admin', 'Management', 'Design Engineer'), productionController.createWorkflowBasedTasks);

router.get('/manufacturing-stages', roleMiddleware('Admin', 'Management', 'Production'), productionController.getManufacturingStages);
router.post('/manufacturing-stages', roleMiddleware('Admin', 'Management'), productionController.createManufacturingStage);
router.put('/manufacturing-stages/:id', roleMiddleware('Admin', 'Management'), productionController.updateManufacturingStage);
router.patch('/manufacturing-stages/:id/status', roleMiddleware('Admin', 'Management', 'Production'), productionController.updateStageStatus);

router.get('/worker-tasks/:stageId', roleMiddleware('Admin', 'Management', 'Production'), productionController.getWorkerTasks);
router.post('/worker-tasks', roleMiddleware('Admin', 'Management'), productionController.createWorkerTask);
router.patch('/worker-tasks/:id/status', roleMiddleware('Admin', 'Management', 'Production'), productionController.updateTaskStatus);

router.get('/statistics', roleMiddleware('Admin', 'Management', 'Production'), productionController.getProductionStatistics);

router.post('/design-projects', roleMiddleware('Admin', 'Management', 'Design Engineer'), productionController.createDesignProject);
router.post('/root-cards/:rootCardId/design-details', roleMiddleware('Admin', 'Management', 'Design Engineer'), productionController.saveDesignProjectDetails);
router.get('/root-cards/:rootCardId/design-details', roleMiddleware('Admin', 'Management', 'Design Engineer'), productionController.getDesignProjectDetails);

router.get('/designs', roleMiddleware('Admin', 'Management', 'Production', 'Design Engineer'), productionController.getAllDesignsWithDetails);
router.get('/designs/:id', roleMiddleware('Admin', 'Management', 'Production', 'Design Engineer'), productionController.getDesignWithDetails);
router.delete('/designs/:id', roleMiddleware('Admin', 'Management', 'Design Engineer'), productionController.deleteDesign);

module.exports = router;
