const express = require('express');
const router = express.Router();
const multer = require('multer');
const path = require('path');
const authMiddleware = require('../../middleware/authMiddleware');
const roleMiddleware = require('../../middleware/roleMiddleware');
const productionController = require('../../controllers/production/productionController');
const designEngineeringController = require('../../controllers/root-cards/designEngineeringController');
const drawingController = require('../../controllers/production/drawingController');
const specificationController = require('../../controllers/production/specificationController');
const technicalFileController = require('../../controllers/production/technicalFileController');

const upload = multer({
  dest: path.join(__dirname, '../../uploads/design-engineering'),
  limits: { fileSize: 50 * 1024 * 1024 }, // 50MB
});

router.use(authMiddleware);

router.get('/root-cards', roleMiddleware('Admin', 'Management', 'Production', 'Design Engineer'), productionController.getProductionRootCards);
router.post('/root-cards', roleMiddleware('Admin', 'Management'), productionController.createProductionRootCard);
router.get('/root-cards/:id', roleMiddleware('Admin', 'Management', 'Production'), productionController.getProductionRootCardById);
router.put('/root-cards/:id', roleMiddleware('Admin', 'Management'), productionController.updateProductionRootCard);
router.patch('/root-cards/:id', roleMiddleware('Admin', 'Management'), productionController.updateProductionRootCard);
router.patch('/root-cards/:id/status', roleMiddleware('Admin', 'Management', 'Production'), productionController.updateProductionRootCardStatus);
router.delete('/root-cards/:id', roleMiddleware('Admin', 'Management'), productionController.deleteProductionRootCard);
router.post('/root-cards/:rootCardId/auto-generate-tasks', roleMiddleware('Admin', 'Management'), productionController.autoGenerateDesignTasks);
router.post('/root-cards/:rootCardId/workflow-tasks', roleMiddleware('Admin', 'Management', 'Design Engineer'), productionController.createWorkflowBasedTasks);
router.post('/root-cards/:id/stages', roleMiddleware('Admin', 'Management'), productionController.createProductionRootCardStage);
router.delete('/root-cards/:id/stages/:stageId', roleMiddleware('Admin', 'Management'), productionController.deleteProductionRootCardStage);

router.get('/manufacturing-stages', roleMiddleware('Admin', 'Management', 'Production'), productionController.getManufacturingStages);
router.post('/manufacturing-stages', roleMiddleware('Admin', 'Management'), productionController.createManufacturingStage);
router.put('/manufacturing-stages/:id', roleMiddleware('Admin', 'Management'), productionController.updateManufacturingStage);
router.patch('/manufacturing-stages/:id/status', roleMiddleware('Admin', 'Management', 'Production'), productionController.updateStageStatus);

router.get('/worker-tasks/:stageId', roleMiddleware('Admin', 'Management', 'Production'), productionController.getWorkerTasks);
router.post('/worker-tasks', roleMiddleware('Admin', 'Management'), productionController.createWorkerTask);
router.patch('/worker-tasks/:id/status', roleMiddleware('Admin', 'Management', 'Production'), productionController.updateTaskStatus);

router.get('/statistics', roleMiddleware('Admin', 'Management', 'Production'), productionController.getProductionStatistics);

// Drawing routes
router.get('/drawings', roleMiddleware('Admin', 'Management', 'Production', 'Design Engineer'), drawingController.getDrawings);
router.post('/drawings', roleMiddleware('Admin', 'Management', 'Design Engineer'), upload.single('file'), drawingController.uploadDrawing);
router.get('/drawings/:id/download', roleMiddleware('Admin', 'Management', 'Production', 'Design Engineer'), drawingController.downloadDrawing);
router.delete('/drawings/:id', roleMiddleware('Admin', 'Management', 'Design Engineer'), drawingController.deleteDrawing);

// Specification routes
router.get('/specifications', roleMiddleware('Admin', 'Management', 'Production', 'Design Engineer'), specificationController.getSpecifications);
router.post('/specifications', roleMiddleware('Admin', 'Management', 'Design Engineer'), upload.single('file'), specificationController.createSpecification);
router.get('/specifications/:id/download', roleMiddleware('Admin', 'Management', 'Production', 'Design Engineer'), specificationController.downloadSpecification);
router.delete('/specifications/:id', roleMiddleware('Admin', 'Management', 'Design Engineer'), specificationController.deleteSpecification);

// Technical Files routes
router.get('/technical-files', roleMiddleware('Admin', 'Management', 'Production', 'Design Engineer'), technicalFileController.getTechnicalFiles);
router.post('/technical-files', roleMiddleware('Admin', 'Management', 'Design Engineer'), upload.single('file'), technicalFileController.createTechnicalFile);
router.get('/technical-files/:id/download', roleMiddleware('Admin', 'Management', 'Production', 'Design Engineer'), technicalFileController.downloadTechnicalFile);
router.delete('/technical-files/:id', roleMiddleware('Admin', 'Management', 'Design Engineer'), technicalFileController.deleteTechnicalFile);

router.post('/root-cards/:rootCardId/design-details', roleMiddleware('Admin', 'Management', 'Design Engineer'), designEngineeringController.createOrUpdate);
router.get('/root-cards/:rootCardId/design-details', roleMiddleware('Admin', 'Management', 'Design Engineer'), designEngineeringController.getDesignEngineering);

// Production Plan routes
router.get('/plans', roleMiddleware('Admin', 'Management', 'Production'), productionController.getProductionPlans);
router.get('/ready-for-production', roleMiddleware('Admin', 'Management', 'Production'), productionController.getReadyForProduction);
router.post('/plans', roleMiddleware('Admin', 'Management'), productionController.createProductionPlan);
router.get('/plans/:id', roleMiddleware('Admin', 'Management', 'Production'), productionController.getProductionPlanById);
router.patch('/plans/:id', roleMiddleware('Admin', 'Management'), productionController.updateProductionPlan);
router.patch('/plans/:id/status', roleMiddleware('Admin', 'Management', 'Production'), productionController.updateProductionPlanStatus);
router.delete('/plans/:id', roleMiddleware('Admin', 'Management'), productionController.deleteProductionPlan);

module.exports = router;
