import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { 
  Plus, 
  Trash2, 
  Edit,
  Download,
  AlertCircle,
  Loader2,
  X
} from 'lucide-react';
import CreateSalesOrderModal from './CreateSalesOrderModal';
import Swal from 'sweetalert2';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const SalesOrderPage = () => {
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState([]);
  const [isModalVisible, setIsModalVisible] = useState(false);
  const [editingOrder, setEditingOrder] = useState(null);

  const fetchData = async () => {
    setLoading(true);
    try {
      const response = await axios.get('/sales/management');
      setData(response.data);
    } catch (error) {
      console.error('Fetch error:', error);
      Swal.fire({
        icon: 'error',
        title: 'Error',
        text: 'Failed to fetch sales orders'
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleEdit = (order) => {
    setEditingOrder(order);
    setIsModalVisible(true);
  };

  const handleDownloadPDF = (order) => {
    const doc = new jsPDF();
    
    // Title
    doc.setFontSize(22);
    doc.setTextColor(40, 44, 52);
    doc.text('SALES ORDER', 105, 20, { align: 'center' });
    
    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(14, 25, 196, 25);
    
    // Order Info
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('SO Number:', 14, 35);
    doc.setTextColor(0, 0, 0);
    doc.setFont(undefined, 'bold');
    doc.text(order.so_number, 40, 35);
    
    doc.setFont(undefined, 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text('Order Date:', 14, 40);
    doc.setTextColor(0, 0, 0);
    doc.text(new Date(order.order_date).toLocaleDateString(), 40, 40);
    
    doc.setTextColor(100, 100, 100);
    doc.text('Delivery Date:', 14, 45);
    doc.setTextColor(0, 0, 0);
    doc.text(new Date(order.delivery_date).toLocaleDateString(), 40, 45);
    
    // Customer Info
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('CUSTOMER DETAILS', 14, 55);
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(order.customer_name, 14, 62);
    
    // Product Table
    const subtotal = Number(order.quantity) * Number(order.unit_price);
    const taxableValue = subtotal - Number(order.discount || 0);
    const taxAmount = (taxableValue * Number(order.tax_percent || 18)) / 100;
    const totalAmount = taxableValue + taxAmount;

    autoTable(doc, {
      startY: 75,
      head: [['Product Description', 'Qty', 'Unit Price', 'Subtotal']],
      body: [
        [
          { content: `${order.product_name}\nCode: ${order.item_code}`, styles: { fontStyle: 'bold' } },
          order.quantity,
          `INR ${Number(order.unit_price).toLocaleString()}`,
          `INR ${subtotal.toLocaleString()}`
        ]
      ],
      theme: 'striped',
      headStyles: { fillColor: [79, 70, 229] }
    });

    // Summary
    const finalY = doc.lastAutoTable.finalY + 10;
    
    doc.setFontSize(10);
    doc.text('Notes:', 14, finalY);
    doc.setFont(undefined, 'italic');
    doc.text(order.notes || 'No special instructions.', 14, finalY + 5, { maxWidth: 100 });

    doc.setFont(undefined, 'normal');
    const summaryX = 140;
    doc.text('Subtotal:', summaryX, finalY);
    doc.text(`INR ${subtotal.toLocaleString()}`, 196, finalY, { align: 'right' });
    
    if (order.discount > 0) {
      doc.setTextColor(220, 38, 38);
      doc.text('Discount:', summaryX, finalY + 5);
      doc.text(`- INR ${Number(order.discount).toLocaleString()}`, 196, finalY + 5, { align: 'right' });
      doc.setTextColor(0, 0, 0);
    }
    
    doc.text(`Tax (${order.tax_percent}%):`, summaryX, finalY + 10);
    doc.text(`INR ${taxAmount.toLocaleString()}`, 196, finalY + 10, { align: 'right' });
    
    doc.setLineWidth(0.5);
    doc.line(summaryX, finalY + 13, 196, finalY + 13);
    
    doc.setFont(undefined, 'bold');
    doc.setFontSize(12);
    doc.text('Total Amount:', summaryX, finalY + 20);
    doc.setTextColor(79, 70, 229);
    doc.text(`INR ${totalAmount.toLocaleString()}`, 196, finalY + 20, { align: 'right' });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Sterling ERP System', 105, 285, { align: 'center' });

    doc.save(`Sales_Order_${order.so_number}.pdf`);
    Swal.fire({
      icon: 'success',
      title: 'Success',
      text: 'PDF Downloaded Successfully',
      timer: 1500,
      showConfirmButton: false
    });
  };

  const handleDelete = async (id) => {
    const result = await Swal.fire({
      title: 'Are you sure?',
      text: "You won't be able to revert this!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#d33',
      cancelButtonColor: '#3085d6',
      confirmButtonText: 'Yes, delete it!'
    });

    if (result.isConfirmed) {
      try {
        await axios.delete(`/sales/management/${id}`);
        Swal.fire('Deleted!', 'Sales Order has been deleted.', 'success');
        fetchData();
      } catch (error) {
        console.error('Delete error:', error);
        Swal.fire('Error!', 'Failed to delete sales order.', 'error');
      }
    }
  };

  const getStatusColor = (status) => {
    const s = status?.toLowerCase();
    switch (s) {
      case 'completed': return 'bg-green-100 text-green-800';
      case 'approved': return 'bg-emerald-100 text-emerald-800';
      case 'cancelled': return 'bg-red-100 text-red-800';
      case 'in progress': 
      case 'in_progress': return 'bg-blue-100 text-blue-800';
      case 'pending': return 'bg-amber-100 text-amber-800';
      default: return 'bg-yellow-100 text-yellow-800';
    }
  };

  return (
    <div className="p-6">
      <div className="bg-white dark:bg-slate-900 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800">
        <div className="p-6 border-b border-slate-200 dark:border-slate-800 flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Sales Orders</h1>
            <p className="text-slate-500 dark:text-slate-400 mt-1">Manage sales orders and track their progress</p>
          </div>
          <button 
            onClick={() => {
              setEditingOrder(null);
              setIsModalVisible(true);
            }}
            className="flex items-center gap-2 bg-primary-600 hover:bg-primary-700 text-white px-4 py-2 rounded-lg transition-colors font-medium"
          >
            <Plus size={20} />
            Create Sales Order
          </button>
        </div>

        <div className="overflow-x-auto">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-12">
              <Loader2 className="w-8 h-8 text-primary-600 animate-spin" />
              <p className="mt-2 text-slate-500">Loading sales orders...</p>
            </div>
          ) : data.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 text-slate-500">
              <AlertCircle className="w-12 h-12 mb-2 opacity-20" />
              <p>No sales orders found</p>
            </div>
          ) : (
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50 dark:bg-slate-800/50 border-b border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 text-sm font-semibold uppercase tracking-wider">
                  <th className="px-6 py-4">SO Number</th>
                  <th className="px-6 py-4">Customer</th>
                  <th className="px-6 py-4">Product</th>
                  <th className="px-6 py-4">Qty</th>
                  <th className="px-6 py-4">Unit Price</th>
                  <th className="px-6 py-4">Total Value</th>
                  <th className="px-6 py-4 text-center">Dates</th>
                  <th className="px-6 py-4">Status</th>
                  <th className="px-6 py-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200">
                {data.map((order) => (
                  <tr key={order.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors">
                    <td className="px-6 py-4">
                      <div className="flex flex-col">
                        <span className="font-bold text-slate-900 dark:text-slate-200">{order.so_number}</span>
                        <span className="text-[10px] text-slate-400 font-mono">{order.root_card_code}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-slate-600 dark:text-slate-400 font-medium">{order.customer_name}</td>
                    <td className="px-6 py-4 text-slate-600 dark:text-slate-400">
                      <div className="flex flex-col">
                        <span className="text-sm">{order.product_name}</span>
                        <span className="text-[10px] text-slate-400 uppercase tracking-tighter">{order.item_code}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-slate-600 dark:text-slate-400 font-bold text-primary-600 dark:text-primary-400 text-center">{order.quantity}</td>
                    <td className="px-6 py-4 text-slate-600 dark:text-slate-400 font-medium italic">₹{Number(order.unit_price).toLocaleString()}</td>
                    <td className="px-6 py-4">
                      <div className="flex flex-col">
                        <span className="text-slate-900 dark:text-slate-200 font-bold">
                          ₹{((Number(order.quantity || 0) * Number(order.unit_price || 0) - Number(order.discount || 0)) * (1 + Number(order.tax_percent || 0) / 100)).toLocaleString()}
                        </span>
                        {order.discount > 0 && (
                          <span className="text-[10px] text-red-500">Incl. ₹{order.discount} discount</span>
                        )}
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex flex-col text-[11px] gap-1">
                        <div className="flex justify-between gap-2">
                          <span className="text-slate-400 uppercase font-bold">Ordered:</span>
                          <span className="text-slate-600 dark:text-slate-400">{new Date(order.order_date).toLocaleDateString()}</span>
                        </div>
                        <div className="flex justify-between gap-2">
                          <span className="text-slate-400 uppercase font-bold">Delivery:</span>
                          <span className="text-primary-600 dark:text-primary-400 font-bold">{new Date(order.delivery_date).toLocaleDateString()}</span>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <span className={`px-2.5 py-1 rounded-full text-[10px] font-bold tracking-wider ${getStatusColor(order.status)} uppercase shadow-sm border border-black/5`}>
                        {order.status || 'PENDING'}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-right">
                      <div className="flex justify-end gap-2">
                        <button 
                          onClick={() => handleDownloadPDF(order)}
                          className="p-2 text-indigo-600 dark:text-indigo-400 hover:bg-indigo-50 dark:hover:bg-indigo-900/30 rounded-lg transition-colors"
                          title="Download PDF"
                        >
                          <Download size={18} />
                        </button>
                        <button 
                          onClick={() => handleEdit(order)}
                          className="p-2 text-primary-600 dark:text-primary-400 hover:bg-primary-50 dark:hover:bg-primary-900/30 rounded-lg transition-colors"
                          title="Edit Order"
                        >
                          <Edit size={18} />
                        </button>
                        <button 
                          onClick={() => handleDelete(order.id)}
                          className="p-2 text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/30 rounded-lg transition-colors"
                          title="Delete Order"
                        >
                          <Trash2 size={18} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>

      {isModalVisible && (
        <CreateSalesOrderModal 
          editData={editingOrder}
          onCancel={() => {
            setIsModalVisible(false);
            setEditingOrder(null);
          }}
          onSuccess={() => {
            setIsModalVisible(false);
            setEditingOrder(null);
            fetchData();
          }}
        />
      )}
    </div>
  );
};

export default SalesOrderPage;
